apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pomerium
          image: pomerium/ingress-controller:sha-7ac72b5
          imagePullPolicy: IfNotPresent
